
<div class="card-user-container">


 <div class="card-user-bio">
    <h2><?php echo $_SESSION['user']->user_name; ?></h2>
    <h3><?php echo $_SESSION['user']->email; ?></h3>
    <a href="/index/change?user_id=<?php echo $_SESSION['user']->user_id ?>">
    <i title="Change" class="fas fa-edit fa-2x"></i></a>
    <a onclick="return confirm('Are you sure you want to delete <?php echo $_SESSION['user']->user_name?>');" href="/index/delete?user_id=<?php echo $_SESSION['user']->user_id ?>">
    <i title="Delete" class="fas fa-trash fa-2x"></i></a>
    <p></p>


  
 