<?php
if(isset($_POST['remember'])){
if($_POST['remember']=='1' || $_POST['remember']=='on')
                    {
                    $time = time() + 3600 * 24 * 7;
                    setcookie('email', $_POST['email'], $time);
                    }
                }
?>

<div>
<a href="/account/picupload">Upload a picture</a>
</div>

<?php/*
    $dir='http://zadatak.hr/public/img/asda';
     $files = glob('http://zadatak.hr/public/img/asda/*');
     print_r($files);
     for ($i=0; $i<count($files); $i++)
      {
        $image = $files[$i];
        $supported_file = array(
                'jpg',
                'png'
         );

         $ext = strtolower(pathinfo($image, PATHINFO_EXTENSION));
         if (in_array($ext, $supported_file)) {
            echo basename($image)."<br />"; // show only image name if you want to show full path then use this code // echo $image."<br />";
             echo '<img src="'.$image .'" alt="Random image" />'."<br /><br />";
            } else {
                continue;
            }
          }
      */ ?>
      <img src="<?php echo APP::config('url'); ?>public/img/asda/1.jpg" 