<form action="/account/upload" method="POST"
enctype="multipart/form-data">
<div>
<label>Picture name<input type="text" name="picture_name" id="picture_name"></label>
<label for="picture">Select picture</label>
  <input type="file" name="picture" id="picture">
  <input type="submit" class="button expanded" 
      value="Upload"></input>
</div>
<input type="hidden" name="user_id" 
  value="<?php echo $_SESSION['user']->user_id;?>">
</form>
<?php
echo $msg;
?>
