<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title">Home</div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
<div class="tob-bar-left"><a href="/">Home</a></div>
    <div class="top-bar-right">
        <ul class="menu">
            <li class="menu-text show-for-large">
            </li>
            <li>
            <?php if(!isset($_SESSION['user'])): ?>
                <a href="/index/login">Login</a>
                <li><a href="/index/register">Registration</a></li>
            <?php else:?>
                <a href="/index/logout">Log out 
                <?php  echo $_SESSION['user']->user_name?></a>
            <?php  endif;?>
                </li>
            <?php if(isset($_SESSION['user'])):?>
                <li><a href="/index/account?user_id=<?php echo $_SESSION['user']->user_id?>">My account</a></li>
                <li><a href="/account/index">Managment</a></li>
            <?php  endif; ?>
        </ul>
    </div>
</div>