<div class="title-bar" data-responsive-toggle="example-animated-menu" data-hide-for="medium">
<button class="menu-icon" type="button" data-toggle></button>
<div class="title-bar-title">Home</div>
</div>
<div class="top-bar" id="example-animated-menu" data-animate="hinge-in-from-top spin-out">
<div class="tob-bar-left"><a href="/">Home</a></div>
    <div class="top-bar-right">
        <ul class="menu">
            <li class="menu-text show-for-large">
            </li>
            <li>
            <?php// if(!isset($_SESSION['admin'])): ?>
                <a href="/index/login">Login</a>
                <li><a href="#">Registration</a></li>
            <?php //else:?>
                <a href="/index/logout">Log out 
                <?php // echo $_SESSION['admin']->username?></a>
            <?php // endif;?>
                </li>
            <?php //if(isset($_SESSION['admin'])):?>
                <li><a href="#">My account</a></li>
                <li><a href="#">Managment</a></li>
            <?php // endif; ?>
        </ul>
    </div>
</div>