<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Foundation | Welcome</title>
    <link rel="stylesheet" href="https://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
    <link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/foundation.css">
    <link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/app.css"> 
    <link rel="apple-touch-icon" sizes="57x57" href="/public/images/favicons/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/public/images/favicons/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/public/images/favicons/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/public/images/favicons/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/public/images/favicons/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/public/images/favicons/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/public/images/favicons/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/public/images/favicons/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/public/images/favicons/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/public/images/favicons/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/public/images/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/public/images/favicons/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/public/images/favicons/favicon-16x16.png">
<link rel="manifest" href="/public/images/favicons/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/public/images/favicons/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">